if (project.ext.has('sfmRepositoriesConfigured')) {
    throw new GradleException("repositories.gradle must not be applied more than once")
}

ext.sfmRepositoriesConfigured = true

repositories {
    // Put repositories for dependencies here
    // ForgeGradle automatically adds the Forge maven and Maven Central for you

    // If you have mod jar dependencies in ./libs, you can declare them as a repository like so.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:flat_dir_resolver
    // flatDir {
    //     dir 'libs'
    // }
    mavenLocal()
    mavenCentral()

    maven {
        name 'jared' // used by newer JEI coordinates
        url 'https://maven.blamejared.com/'
    }

    maven {
        name 'jei' // used by older JEI coordinates
        url 'https://dvs1.progwml6.com/files/maven'
    }

    maven {
        name 'CurseMaven'
        url 'https://www.cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }

    maven {
        name 'mekanism'
        url 'https://modmaven.dev/'
    }

    maven {
        name 'thermal'
        url 'https://maven.covers1624.net/'
        // https://nexus.covers1624.net/#browse/browse:cofh-releases
    }
}
